### ISSUE TITLE
feedback from test release 19

### ISSUE THREAD

**Issue by cpg** [sukhbir-singh/rsnapshot-backup-plugin#1]
* the URL name immediately after installing is "weird"
* the error message when there is no / at the end of a backup path does not tell the user what they should do, i.e. what is the error. the user has no idea. it may be good if the code can check if the path exists *and* it's a directory and if so, it adds a / internally (most user will never know to put a /)
* use `./` instead of `localhost/` in the generated configuration
* explore the use /etc/cron.daily/ *only*. i.e. to put the crontab file there as one and only one crontab interface
* do not list hourly (too crazy, too much disk/CPU, potentially), instead, interval should be: Daily (the default), Weekly, Monthly
* do not use alpha/beta/gamma, use daily/weekly/monthly
* retaining: daily 14, weekly 8, monthly 24 
* do not label it Interval 
* use logfile /var/log/rsnapshot.log

UI:
* there should be more separation between the areas in the page (use markup/ideas form other pages like Setup > Settings, etc.)
* too many red buttons, red button in the first page should be a link
* remove the word "automatic" from the start button
* when pressing the start button, we should have a confirmation "This will start automatic backups of the folders entered, with the periodicity selected above. Are you sure you want to continue?"
* the alignment of labels (left side) should be "top"
* label to fieldset should be `Edit Settings` (from `Edit Rsnapshot Settings`)
* there should be some separation to the bottom button. looks like it's aligned to interval

maybe we need a good user visible name for it

**Comment by sukhbir-singh** [comment]
I did all these changes in the plugin. you can try `test release 28`.
